### ISSUE TITLE
Fix related accelerator links

### ISSUE THREAD

**Issue by Jbetts05** [microsoft/dstoolkit-web#108]
3 main changes needed: 
1) In script-setsingleaaccleratorpagecontents.js, add /dstoolkit-web/ before each link so instead of /forecasting/ have /dstoolkit-web/forecasting/
2) In each accelerator page, add /dstoolkit-web/ for the listLinksRelatedAccelerators const so instead of /ml-ops/ have /dstoolkit-web/ml-ops/
3) update knowledge mining to use the Github Pages page and not the Github Repo for KM in setsingleaaccleratorpagecontents.js

**Comment by strobaek** [comment]
Hi,
Do you have to prefix with 'dstoolkit-web'? Would it not be possible to prefix with 'site.baseurl'? 
To make it more generic?

**Comment by Jbetts05** [comment]
@strobaek possibly yeah, does the displayName get updated when using {{site.baseurl}}? For the example of forecasting, is the button name still labelled with 'dstoolkit-web/forecasting' or does it change to 'Forecasting Accelerator'?

**Comment by strobaek** [comment]
@Jbetts05 
Fixed it another way in the js-file, so we keep the accelerator pages simple. I'll assign you as reviewer soon :)

**Comment by strobaek** [comment]
@Jbetts05 
Re. 3.
Not quite sure what link. Variable linkAccessAcceleratorRepo should point to the GitHub repo (and not page).
Is it the links in [].js for the Related Accelerators?

**Comment by Jbetts05** [comment]
@strobaek just here: script-setsingleacceleratorpagecontents.js line 119. Should this be /knowledge-mining/? 

<img width="414" alt="image" src="https://user-images.githubusercontent.com/52085471/178158602-43054546-d73a-4923-94da-d6bacf3cbc2d.png">

**Comment by strobaek** [comment]
Fixed with another push. Guess I screwed up there.
